// @flow

// A-Ö
export default {
  alkohollag: 'Alkohollag',
  anhållen: 'Anhållen',
  arbetsplatsolycka: 'Arbetsplatsolycka',
  bedrägeri: 'Bedrägeri',
  bostadsinbrott: 'Bostadsinbrott',
  brand: 'Brand',
  brott: 'Brott',
  brott_i_nära_relation: 'Brott i nära relation',
  brottsplatsundersökning: 'Brottsplatsundersökning',
  bråk: 'Bråk',
  detonation: 'Detonation',
  dråp: 'Dråp',
  dråp_alt: 'Dråp/',
  efterlyst: 'Efterlyst',
  eldningsförbud: 'Eldningsförbud',
  envarsgripande: 'Envarsgripande',
  farligt_föremål: 'Farligt föremål',
  fickstölder_och_bagagestölder: 'Fickstölder och bagagestölder',
  fjällräddning: 'Fjällräddning',
  fylleri_LOB: 'Fylleri/LOB',
  grov: 'grov',
  grov_misshandel: 'Grov misshandel',
  inbrott: 'Inbrott',
  inbrott_alt: '/inbrott',
  knivlagen: 'Knivlagen',
  kontroll_person: 'Kontroll person',
  larm: 'Larm',
  missbruk_av_urkund: 'Missbruk av urkund',
  misshandel: 'Misshandel',
  mord: 'Mord',
  mord_alt: 'Mord/',
  narkotikabrott: 'Narkotikabrott',
  ordningslagen: 'Ordningslagen',
  olaga_hot: 'Olaga hot',
  polisinsats_kommendering: 'Polisinsats/kommendering',
  rattfylleri: 'Rattfylleri',
  räddningsinsats: 'Räddningsinsats',
  rån: 'Rån',
  stöld: 'Stöld',
  stöld_inbrott: 'Stöld/inbrott',
  skottlossning: 'Skottlossning',
  skadegörelse: 'Skadegörelse',
  sedlighetsbrott: 'Sedlighetsbrott',
  trafikolycka: 'Trafikolycka',
  trafikhinder: 'Trafikhinder',
  trafikbrott: 'Trafikbrott',
  trafikkontroll: 'Trafikkontroll',
  vapenlagen: 'Vapenlagen',
  våld_hot_mot_tjänsteman: 'Våld/hot mot tjänsteman',
  våldtäkt: 'Våldtäkt',
  vilt: 'vilt',
  vilt_olycka: 'Viltolycka'
}
